### ISSUE TITLE
Data가 안 보여요.

### ISSUE THREAD

**Issue by NoSyu** [adobecs5/urp2015#1]
우리끼리만 쓰는 것이니 한국어로 진행할까요? ㅎㅎ

메일에 데이터가 있다고 하나 clone 해보니 안 보여서요.ㅜ
push 부탁해요~

**Comment by adobecs5** [comment]
헉 푸쉬했습니다. 죄송합니다 해해

**Comment by NoSyu** [comment]
확인했어요. :+1:
